server:
  port: 8181

eureka:
  client:
    healthcheck:
      enabled: true #开启健康检查（需要spring-boot-starter-actuator依赖）
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
    registry-fetch-interval-seconds: 10 # 从服务端获取时间注册信息时间间隔
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 10 # 续约更新时间间隔（默认30秒）
    lease-expiration-duration-in-seconds: 30 # 续约到期时间（默认90秒）
    #leaseExpirationDurationInSeconds，表示eureka server至上一次收到client的心跳之后，
    #等待下一次心跳的超时时间，在这个时间内若没收到下一次心跳，则将移除该instance
    #如果该值太大，则很可能将流量转发过去的时候，该instance已经不存活了。
    #如果该值设置太小了，则instance则很可能因为临时的网络抖动而被摘除掉。
    #该值至少应该大于leaseRenewalIntervalInSeconds

    #leaseRenewalIntervalInSeconds，表示eureka client发送心跳给server端的频率。
    #如果在leaseExpirationDurationInSeconds后，server端没有收到client的心跳，则将摘除该instance。
    #除此之外，如果该instance实现了HealthCheckCallback，并决定让自己unavailable的话，则该instance也不会接收到流量。
    #默认30秒


spring:
  application:
    name: client
  messages:
      encoding: UTF-8
  http:
    encoding:
      enabled: true
      charset: UTF-8
  banner:
    charset: UTF-8