package com.whale.xinyan.entity;

import com.whale.common.bean.IdEntity;
import lombok.Data;

import javax.persistence.*;

/**
 * generated by Generate POJOs.groovy
 * <p>Date: Thu Jun 06 11:34:45 CST 2019.</p>
 *
 * @author Chaui
 */
@Data
@Entity
@Table(name = "lwl_loan_totaldebt_detail")
public class LoanTotaldebtDetail extends IdEntity {

    /**
     * 历史共债ID
     */
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name = "totaldebt_detail_id")
    private Integer totaldebtDetailId;

    /**
     * 共债档案ID
     */
    @Column(name = "totaldebt_id")
    private Integer totaldebtId;

    /**
     * 借款ID
     */
    @Column(name = "loan_id")
    private Integer loanId;

    /**
     * 用户ID
     */
    @Column(name = "uid")
    private Integer uid;

    /**
     * 共债统计时间范围
     */
    @Column(name = "totaldebt_date")
    private String totaldebtDate;

    /**
     * 共债机构数
     */
    @Column(name = "totaldebt_org_count")
    private String totaldebtOrgCount;

    /**
     * 共债订单数
     */
    @Column(name = "totaldebt_order_count")
    private String totaldebtOrderCount;

    /**
     * 共债订单已还款金额
     */
    @Column(name = "totaldebt_order_amt")
    private String totaldebtOrderAmt;

    /**
     * 疑似借新还旧 Y/N
     */
    @Column(name = "new_or_old")
    private String newOrOld;

    /**
     * 共债订单金额
     */
    @Column(name = "totaldebt_order_lend_amt")
    private String totaldebtOrderLendAmt;

}
