package com.whale.xinyan.entity;

import com.whale.common.bean.IdEntity;
import lombok.Data;

import javax.persistence.*;

/**
 * generated by Generate POJOs.groovy 
 * <p>Date: Mon Jun 10 14:16:40 CST 2019.</p>
 *
 * @author Chaui
 */
@Data
@Entity
@Table ( name ="lwl_loan_overdue_record_details" )
public class LwlLoanOverdueRecordDetails extends IdEntity {


	private static final long serialVersionUID =  8412464639823387795L;


	/**
	 * 逾期档案明细ID
	 */
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "overdue_details_id" )
	private Integer overdueDetailsId;

	/**
	 * 逾期档案ID
	 */
	@Column(name = "overdue_id" )
	private Integer overdueId;

	/**
	 * 逾期时间
	 */
	@Column(name = "date" )
	private String date;

	/**
	 * 逾期账期数
	 */
	@Column(name = "count" )
	private String count;

	/**
	 * 逾期金额
	 */
	@Column(name = "amount" )
	private String amount;

	/**
	 * 是否结清
	 */
	@Column(name = "settlement" )
	private String settlement;
}
