package com.whale.xinyan.entity;

import com.whale.common.bean.IdEntity;
import lombok.Data;

import javax.persistence.*;

/**
 * generated by Generate POJOs.groovy 
 * <p>Date: Mon Jun 10 14:16:31 CST 2019.</p>
 *
 * @author Chaui
 */
@Data
@Entity
@Table ( name ="lwl_loan_overdue_record" )
public class LwlLoanOverdueRecord extends IdEntity {


	/**
	 * 逾期档案ID
	 */
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "overdue_id" )
	private Integer overdueId;

	/**
	 * 借款ID
	 */
	@Column(name = "loan_id" )
	private Integer loanId;

	/**
	 * 用户ID
	 */
	@Column(name = "uid" )
	private Integer uid;

	/**
	 * 逾期机构数
	 */
	@Column(name = "member_count" )
	private String memberCount;

	/**
	 * 逾期订单数
	 */
	@Column(name = "order_count" )
	private String orderCount;

	/**
	 * 逾期总金额
	 */
	@Column(name = "debt_amount" )
	private String debtAmount;

}
