server:
  port: 8680

spring:
  cloud:
    stream:
      bindings:
        input:
          destination: cloud-stream
          binder: local_rabbit
          content-type: text/plain  # 设置消息类型，本次为文本 text/plain，如果是json对象则设置“application/json”
        output:
          destination: cloud-stream
          binder: local_rabbit
          content-type: text/plain
      binders:
        local_rabbit: # 表示定义的名称，用于于binding 的 binder整合
          type: rabbit # 消息组件类型
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
                virtual-host: /