server:
  port: 8280
  tomcat:
    uri-encoding: UTF-8

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

spring:
  application:
    name: ribbon
  messages:
    encoding: UTF-8
  http:
    encoding:
      enabled: true
      charset: UTF-8


#ribbon:
#  httpclient:
#    enabled: false
#  okhttp:
#    enabled: true
#  ReadTimeout: 1000
#  ConnectTimeout: 1000
#  # 同一实例最大重试次数，不包括首次调用
#  MaxAutoRetries: 1
#  # 重试其他实例的最大重试次数，不包括首次所选的server
#  MaxAutoRetriesNextServer: 2
#  # 是否所有操作都进行重试
#  OkToRetryOnAllOperations: false


hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 6000

