server:
  port: 8762
  servlet:
    context-path: /eureka-client

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka-server/eureka/

spring:
  application:
    name: service-hi