server:
  port: 8001

logging:
  config: classpath:log4j2.xml

spring:
  application:
    name: provider
  datasource:
    #driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://47.100.185.77:3306/qin?characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&connectTimeout=1000&socketTimeout=3000&serverTimezone=GMT%2B8
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://47.100.185.77:3306/qin?characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&connectTimeout=1000&socketTimeout=3000&serverTimezone=GMT%2B8
    username: root
    password: 373616885
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      auto-commit: true
      minimum-idle: 0
      maximum-pool-size: 10
      connection-timeout: 6000
      connection-test-query: select 1 from dual
      idle-timeout: 10000
      max-lifetime: 30000

mybatis:
  mapper-locations: classpath:com/qin/provider/xml/*.xml
