eureka:
  client:
    service-url:
      defaultZone: http://47.112.117.58:8761/eureka/
  instance:
    hostname: data-xinyan
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

spring:

  application:
    name: data-xinyan


  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://rm-wz94yuc2439xajx14.mysql.rds.aliyuncs.com:3306/little_whale_loan?useUnicode=true&characterEncoding=UTF-8&useSSL=false&useAffectedRows=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: xjjk
    password: Xjjk189@
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 15
      connection-test-query: select 1 from dual
      connection-timeout: 6000

  jpa:
    show-sql: false


  ## 新颜探针A配置
  xinyan:
    host: https://api.xinyan.com/product/negative/v4/black
    merchNo: 8150728780
    pfxPwd: whale_123456
    pfxPath: /home/app/files/whale_pri.pfx
    cerPath: /home/app/files/whale_pub.cer