server:
  port: 8500

spring:
  profiles:
    active: dev

  jpa:
    hibernate:
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    database: MYSQL
    generate-ddl: false
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        dialect: org.hibernate.dialect.MySQL5Dialect
    open-in-view: false
  main:
    allow-bean-definition-overriding: true

