server:
  port: 8401

logging:
  config: classpath:log4j2.xml

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/,http://localhost:9002/eureka/,http://localhost:9003/eureka/
  instance:
    # eureka \u670D\u52A1\u540D\u79F0\u7684\u4FEE\u6539
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    # \u663E\u793A\u8DEF\u5F84\u663E\u793AIP
    prefer-ip-address: true
    # \u6BCF\u95F4\u96941s\uFF0C\u5411\u670D\u52A1\u7AEF\u53D1\u9001\u4E00\u6B21\u5FC3\u8DF3\uFF0C\u8BC1\u660E\u81EA\u5DF1\u4F9D\u7136\u201D\u5B58\u6D3B\u201C\u3002
    lease-renewal-interval-in-seconds: 1
    # \u544A\u8BC9\u670D\u52A1\u7AEF\uFF0C\u5982\u679C\u62112s\u4E4B\u5185\u6CA1\u6709\u7ED9\u4F60\u53D1\u5FC3\u8DF3\uFF0C\u5C31\u4EE3\u8868\u6211\u201C\u6B7B\u201D\u4E86\uFF0C\u5C06\u6211\u8E22\u51FA\u6389\u3002
    lease-expiration-duration-in-seconds: 2


spring:
  application:
    name: provider
  datasource:
    #driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://47.100.185.77:3306/qin?characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&connectTimeout=1000&socketTimeout=3000&serverTimezone=GMT%2B8
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://47.100.185.77:3306/qin?characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&connectTimeout=1000&socketTimeout=3000&serverTimezone=GMT%2B8
    username: root
    password: 373616885
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      auto-commit: true
      minimum-idle: 0
      maximum-pool-size: 10
      connection-timeout: 6000
      connection-test-query: select 1 from dual
      idle-timeout: 10000
      max-lifetime: 30000

mybatis:
  mapper-locations: classpath:com/qin/provider/xml/*.xml

info:
  app:
    name: ${spring.application.name}-${management.server.port}
  company:
    name: qinjp
  build:
    artifactId: $project.artifactId$
    version: $project.version$

# \u66B4\u9732\u6240\u6709\u7AEF\u70B9
management:
  endpoint:
    shutdown:
      # post \u8BF7\u6C42
      enabled: false
    health:
      show-details: always
  endpoints:
    web:
      #base-path: /application
      exposure:
        # * \u5728yaml \u6587\u4EF6\u5C5E\u4E8E\u5173\u952E\u5B57
        include: "*"
        exclude: env
  server:
    port: 8005
    servlet:
      context-path: /management # \u53EA\u6709\u5728\u8BBE\u7F6E\u4E86 management.server.port \u65F6\u624D\u6709\u6548
